version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: food-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "0000"
      MYSQL_DATABASE: foods
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql-data: